# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25a2de4085abefd2ceeb87bbac71c43695481aad1122e8f98c87f8b1a4c4005433561cf99b3b62c24a85b2f58cee69cfae7a3841bef053db2f4b3ce40afdac75

test:
  secret_key_base: ca7b12e3f30065fdda76f351cb41a84ce3cd1dac3cb5131c0437c750986ec191b30371b8b18db7cc6dfb2091715e4d29c1fafe06504fa32c28e520a5254accd2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
